# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataLayerAccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("developer", "Developer"),
                            ("readonly", "Read-Only"),
                        ],
                        default="readonly",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("reason", models.TextField(help_text="Why do you need access?")),
                (
                    "intended_use",
                    models.TextField(
                        blank=True, help_text="How will you use this access?", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_user_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Layer Access Request",
                "verbose_name_plural": "Data Layer Access Requests",
                "db_table": "data_layer_access_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataLayerAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("action", models.CharField(max_length=50)),
                ("resource_type", models.CharField(max_length=50)),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Data Layer Audit Log",
                "verbose_name_plural": "Data Layer Audit Logs",
                "db_table": "data_layer_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataLayerUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password_hash", models.CharField(max_length=128)),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("developer", "Developer"),
                            ("readonly", "Read-Only"),
                        ],
                        default="readonly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("login_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Data Layer User",
                "verbose_name_plural": "Data Layer Users",
                "db_table": "data_layer_users",
                "ordering": ["-created_at"],
            },
        ),
    ]
