# Generated by Django 4.2.29 on 2026-03-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_layer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalayeruser",
            name="is_default_password",
            field=models.BooleanField(
                default=True,
                help_text="True if user hasn't changed their default password",
            ),
        ),
    ]
