# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                (
                    "credential_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("credential_url", models.URLField(blank=True, null=True)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("does_not_expire", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "certifications",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("certificate", "Certificate"),
                            ("diploma", "Diploma"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("doctorate", "Doctorate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "education",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("elementary", "Elementary"),
                            ("limited_working", "Limited Working"),
                            ("professional_working", "Professional Working"),
                            ("full_professional", "Full Professional"),
                            ("native", "Native/Bilingual"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_native", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "languages",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("soft", "Soft Skills"),
                            ("language", "Language"),
                            ("tool", "Tool/Software"),
                            ("industry", "Industry Knowledge"),
                            ("other", "Other"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TalentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("junior", "Junior (2-4 years)"),
                            ("mid", "Mid-Level (4-7 years)"),
                            ("senior", "Senior (7-10 years)"),
                            ("lead", "Lead/Principal (10+ years)"),
                            ("executive", "Executive"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("actively_looking", "Actively Looking"),
                            ("open_to_offers", "Open to Offers"),
                            ("not_looking", "Not Looking"),
                        ],
                        default="open_to_offers",
                        max_length=20,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                ("preferred_job_types", models.JSONField(blank=True, default=list)),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                (
                    "remote_preference",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "salary_expectation_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_expectation_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="ZAR", max_length=3)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("portfolio_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("profile_completeness", models.IntegerField(default=0)),
                (
                    "profile_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Talent Profile",
                "verbose_name_plural": "Talent Profiles",
                "db_table": "talent_profiles",
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experience",
                        to="profiles.talentprofile",
                    ),
                ),
                (
                    "skills_used",
                    models.ManyToManyField(
                        blank=True, related_name="work_experiences", to="profiles.skill"
                    ),
                ),
            ],
            options={
                "db_table": "work_experience",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TalentSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("endorsements_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="profiles.talentprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_skills",
                        to="profiles.skill",
                    ),
                ),
            ],
            options={
                "db_table": "talent_skills",
                "ordering": ["-is_primary", "-proficiency", "-years_of_experience"],
            },
        ),
    ]
