# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="talentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="profiles.skill",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="profiles.talentprofile",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="profiles.talentprofile",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="profiles.talentprofile",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="certifications", to="profiles.skill"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="talentskill",
            unique_together={("profile", "skill")},
        ),
        migrations.AlterUniqueTogether(
            name="language",
            unique_together={("profile", "language")},
        ),
    ]
