# Generated by Django 4.2.29 on 2026-03-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_age_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_data_processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "High School / Matric"),
                    ("certificate", "Certificate / Diploma"),
                    ("bachelors", "Bachelor's Degree"),
                    ("masters", "Master's Degree"),
                    ("doctorate", "Doctorate / PhD"),
                    ("self_taught", "Self-taught / Bootcamp"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="opportunity_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
