# Generated by Django 4.2.29 on 2026-03-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_update_gender_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="consent_authorized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
