# Generated by Django 4.2.29 on 2026-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_consent_authorized_user_job_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="consent_authorized",
        ),
        migrations.RemoveField(
            model_name="user",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="user",
            name="organization_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("talent", "Talent"), ("admin", "Admin")],
                default="talent",
                max_length=20,
            ),
        ),
    ]
