# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("delete", "Delete"),
                            ("share", "Share"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "file_access_logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("password", models.CharField(blank=True, max_length=128)),
                ("max_downloads", models.PositiveIntegerField(blank=True, null=True)),
                ("current_downloads", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "share_links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StorageBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("protected", "Protected"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("max_file_size", models.BigIntegerField(default=104857600)),
                ("allowed_extensions", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("total_size", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_buckets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("extension", models.CharField(blank=True, max_length=20)),
                ("size", models.BigIntegerField(default=0)),
                ("storage_path", models.CharField(max_length=500)),
                ("storage_url", models.URLField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("available", "Available"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                            ("error", "Error"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="storage.storagebucket",
                    ),
                ),
            ],
            options={
                "db_table": "stored_files",
                "ordering": ["-created_at"],
            },
        ),
    ]
