# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stored_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_share_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sharelink",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to="storage.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="fileaccess",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="storage.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="fileaccess",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["bucket", "-created_at"], name="stored_file_bucket__36642e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["owner", "-created_at"], name="stored_file_owner_i_ec5bc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(fields=["status"], name="stored_file_status_bb954a_idx"),
        ),
        migrations.AddIndex(
            model_name="storedfile",
            index=models.Index(
                fields=["content_type"], name="stored_file_content_d9fc31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(fields=["token"], name="share_links_token_5e7a57_idx"),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["file", "-created_at"], name="share_links_file_id_691b8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileaccess",
            index=models.Index(
                fields=["file", "-accessed_at"], name="file_access_file_id_ed8ffc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileaccess",
            index=models.Index(
                fields=["user", "-accessed_at"], name="file_access_user_id_aa8b89_idx"
            ),
        ),
    ]
