# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="interviews_conducted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="applicationstatushistory",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="applications.application",
            ),
        ),
        migrations.AddField(
            model_name="applicationstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "created_at"], name="application_status_91af05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["opportunity", "status"], name="application_opportu_5d13f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "status"], name="application_user_id_4cfcce_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("user", "opportunity")},
        ),
    ]
