# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CVParseResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_file_url", models.URLField()),
                ("source_file_name", models.CharField(max_length=255)),
                ("extracted_name", models.CharField(blank=True, max_length=200)),
                ("extracted_email", models.EmailField(blank=True, max_length=254)),
                ("extracted_phone", models.CharField(blank=True, max_length=50)),
                ("extracted_location", models.CharField(blank=True, max_length=200)),
                ("extracted_summary", models.TextField(blank=True)),
                ("experience", models.JSONField(blank=True, default=list)),
                ("education", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("raw_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cv_parse_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntelligenceInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insight_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_actionable", models.BooleanField(default=True)),
                ("action_url", models.URLField(blank=True)),
                ("action_label", models.CharField(blank=True, max_length=100)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("is_viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "intelligence_insights",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillExtraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_text", models.TextField()),
                ("source_type", models.CharField(max_length=50)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("extracted_skills", models.JSONField(default=list)),
                ("confidence_scores", models.JSONField(default=dict)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "skill_extractions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillTaxonomy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("normalized_name", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("related_skills", models.JSONField(blank=True, default=list)),
                ("demand_score", models.FloatField(default=0.0)),
                ("trend", models.CharField(default="stable", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Skill Taxonomies",
                "db_table": "skill_taxonomy",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TalentScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.FloatField(default=0.0)),
                ("skills_score", models.FloatField(default=0.0)),
                ("experience_score", models.FloatField(default=0.0)),
                ("education_score", models.FloatField(default=0.0)),
                ("completeness_score", models.FloatField(default=0.0)),
                ("engagement_score", models.FloatField(default=0.0)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "talent_scores",
                "ordering": ["-overall_score"],
            },
        ),
    ]
