# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="talentscore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talent_scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="skilltaxonomy",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="intelligence.skilltaxonomy",
            ),
        ),
        migrations.AddIndex(
            model_name="skillextraction",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="skill_extra_source__5469be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skillextraction",
            index=models.Index(
                fields=["-created_at"], name="skill_extra_created_4fc731_idx"
            ),
        ),
        migrations.AddField(
            model_name="intelligenceinsight",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intelligence_insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cvparseresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cv_parses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="talentscore",
            index=models.Index(
                fields=["user", "-calculated_at"], name="talent_scor_user_id_8c5537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="talentscore",
            index=models.Index(
                fields=["-overall_score"], name="talent_scor_overall_f065ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intelligenceinsight",
            index=models.Index(
                fields=["user", "-created_at"], name="intelligenc_user_id_82d529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intelligenceinsight",
            index=models.Index(
                fields=["insight_type"], name="intelligenc_insight_a11200_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intelligenceinsight",
            index=models.Index(
                fields=["is_dismissed", "valid_until"],
                name="intelligenc_is_dism_caa5e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cvparseresult",
            index=models.Index(
                fields=["user", "-created_at"], name="cv_parse_re_user_id_8cdb45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cvparseresult",
            index=models.Index(fields=["status"], name="cv_parse_re_status_a5c3c0_idx"),
        ),
    ]
