# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_path", models.CharField(max_length=500)),
                ("page_title", models.CharField(blank=True, max_length=200)),
                ("referrer", models.URLField(blank=True, max_length=1000)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("scroll_depth", models.PositiveIntegerField(default=0)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "analytics_page_views",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformMetricSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=100,
                    ),
                ),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("verified_users", models.PositiveIntegerField(default=0)),
                ("total_opportunities", models.PositiveIntegerField(default=0)),
                ("active_opportunities", models.PositiveIntegerField(default=0)),
                ("new_opportunities", models.PositiveIntegerField(default=0)),
                ("filled_opportunities", models.PositiveIntegerField(default=0)),
                ("total_applications", models.PositiveIntegerField(default=0)),
                ("new_applications", models.PositiveIntegerField(default=0)),
                ("accepted_applications", models.PositiveIntegerField(default=0)),
                ("rejected_applications", models.PositiveIntegerField(default=0)),
                ("total_logins", models.PositiveIntegerField(default=0)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("avg_session_duration", models.FloatField(default=0.0)),
                ("metrics_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_metric_snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("user_activity", "User Activity"),
                            ("application_stats", "Application Statistics"),
                            ("opportunity_performance", "Opportunity Performance"),
                            ("revenue", "Revenue"),
                            ("custom", "Custom Report"),
                        ],
                        default="custom",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("event_category", models.CharField(blank=True, max_length=100)),
                ("event_label", models.CharField(blank=True, max_length=200)),
                ("event_value", models.FloatField(blank=True, null=True)),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("page_path", models.CharField(blank=True, max_length=500)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "analytics_user_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
