# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="platformmetricsnapshot",
            index=models.Index(
                fields=["-snapshot_date"], name="analytics_m_snapsho_4e71e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformmetricsnapshot",
            index=models.Index(
                fields=["metric_type", "-snapshot_date"],
                name="analytics_m_metric__b19424_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="platformmetricsnapshot",
            unique_together={("snapshot_date", "metric_type")},
        ),
        migrations.AddField(
            model_name="pageview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="page_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["user", "-created_at"], name="analytics_u_user_id_0c1e19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="analytics_u_event_t_66ba6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["event_category", "-created_at"],
                name="analytics_u_event_c_3631aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userevent",
            index=models.Index(
                fields=["session_id"], name="analytics_u_session_d476d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="analytics_r_created_62c876_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "-created_at"],
                name="analytics_r_report__007636_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="analytics_r_status_4dcdd6_idx"),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user", "-created_at"], name="analytics_p_user_id_76d78e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_path", "-created_at"],
                name="analytics_p_page_pa_bf2e00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session_id"], name="analytics_p_session_3152bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["-created_at"], name="analytics_p_created_ea2e48_idx"
            ),
        ),
    ]
