# Generated by Django 4.2.29 on 2026-03-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="industry_other",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="initial_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="interest_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="organization",
            name="referral_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Technology"),
                    ("finance", "Finance & Banking"),
                    ("healthcare", "Healthcare"),
                    ("education", "Education"),
                    ("manufacturing", "Manufacturing"),
                    ("consulting", "Consulting"),
                    ("retail", "Retail & E-commerce"),
                    ("media", "Media & Entertainment"),
                    ("agriculture", "Agriculture"),
                    ("energy", "Energy & Utilities"),
                    ("transportation", "Transportation"),
                    ("hospitality", "Hospitality"),
                    ("legal", "Legal Services"),
                    ("ngo", "NGO / Non-Profit"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("startup", "Startup"),
                    ("non_profit", "Non-Profit"),
                    ("government", "Government"),
                    ("educational", "Educational"),
                    ("ngo", "NGO"),
                    ("other", "Other"),
                ],
                default="company",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 employee"),
                    ("1-10", "1-10 employees"),
                    ("11-50", "11-50 employees"),
                    ("51-200", "51-200 employees"),
                    ("201-500", "201-500 employees"),
                    ("500+", "500+ employees"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
