# Generated by Django 4.2.29 on 2026-03-26 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_industry_other_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="owner",
        ),
        migrations.AddField(
            model_name="organization",
            name="owner_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="PartnerUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("manager", "Hiring Manager"),
                            ("recruiter", "Recruiter"),
                            ("member", "Team Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("can_post_opportunities", models.BooleanField(default=True)),
                ("can_manage_applications", models.BooleanField(default=True)),
                ("can_manage_team", models.BooleanField(default=False)),
                ("can_manage_settings", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("consent_authorized", models.BooleanField(default=False)),
                ("consent_terms_accepted", models.BooleanField(default=False)),
                ("consent_data_processing", models.BooleanField(default=False)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "two_factor_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_password_change", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_users",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner User",
                "verbose_name_plural": "Partner Users",
                "db_table": "partner_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("device_type", models.CharField(blank=True, max_length=20, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="organizations.partneruser",
                    ),
                ),
            ],
            options={
                "db_table": "partner_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerPasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to="organizations.partneruser",
                    ),
                ),
            ],
            options={
                "db_table": "partner_password_reset_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerLoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("locked", "Account Locked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to="organizations.partneruser",
                    ),
                ),
            ],
            options={
                "db_table": "partner_login_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerEmailVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to="organizations.partneruser",
                    ),
                ),
            ],
            options={
                "db_table": "partner_email_verification_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="partneruser",
            index=models.Index(fields=["email"], name="partner_use_email_1a1d20_idx"),
        ),
        migrations.AddIndex(
            model_name="partneruser",
            index=models.Index(
                fields=["organization"], name="partner_use_organiz_61df41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partneruser",
            index=models.Index(fields=["role"], name="partner_use_role_25cd9d_idx"),
        ),
        migrations.AddIndex(
            model_name="partneruser",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="partner_use_is_acti_2e8ea5_idx",
            ),
        ),
    ]
