# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("key_prefix", models.CharField(db_index=True, max_length=10)),
                (
                    "key_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("allowed_ips", models.JSONField(blank=True, default=list)),
                ("allowed_origins", models.JSONField(blank=True, default=list)),
                ("rate_limit", models.PositiveIntegerField(default=1000)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True, unique=True),
                ),
                ("ip_range", models.CharField(blank=True, max_length=50)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("abuse", "Abuse"),
                            ("spam", "Spam"),
                            ("bruteforce", "Brute Force"),
                            ("malicious", "Malicious Activity"),
                            ("manual", "Manual Block"),
                            ("other", "Other"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_permanent", models.BooleanField(default=False)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("block_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "blocked_ips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of Service"),
                            ("privacy_policy", "Privacy Policy"),
                            ("marketing", "Marketing Communications"),
                            ("data_processing", "Data Processing"),
                            ("cookies", "Cookies"),
                            ("third_party_sharing", "Third-party Sharing"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("is_granted", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "consent_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RateLimitLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("endpoint", models.CharField(max_length=500)),
                ("limit_type", models.CharField(max_length=50)),
                ("limit_value", models.PositiveIntegerField()),
                ("current_count", models.PositiveIntegerField()),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "rate_limit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_failed", "Failed Login"),
                            ("login_suspicious", "Suspicious Login"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("invalid_token", "Invalid Token"),
                            ("data_breach_attempt", "Data Breach Attempt"),
                            ("sql_injection", "SQL Injection Attempt"),
                            ("xss_attempt", "XSS Attempt"),
                            ("bruteforce", "Brute Force Attack"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("description", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "security_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
