# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityevent",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_security_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consentrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blockedip",
            name="blocked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_ips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="security_ev_event_t_33b3e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="security_ev_severit_768a26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["is_resolved", "-created_at"],
                name="security_ev_is_reso_abc463_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="security_ev_ip_addr_48a73a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitlog",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="rate_limit__ip_addr_8029df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitlog",
            index=models.Index(
                fields=["user", "-created_at"], name="rate_limit__user_id_1a0b17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratelimitlog",
            index=models.Index(
                fields=["endpoint", "-created_at"],
                name="rate_limit__endpoin_7da6d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["user", "consent_type"], name="consent_rec_user_id_5843c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["user", "-created_at"], name="consent_rec_user_id_56f186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["consent_type", "version"],
                name="consent_rec_consent_10535a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blockedip",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="blocked_ips_is_acti_f78f89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["user", "is_active"], name="api_keys_user_id_6e7352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["key_prefix"], name="api_keys_key_pre_9c2634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["is_active", "expires_at"], name="api_keys_is_acti_f90a04_idx"
            ),
        ),
    ]
