# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("summary", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField()),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("internship", "Internship"),
                            ("volunteer", "Volunteer"),
                            ("apprenticeship", "Apprenticeship"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior"),
                            ("mid", "Mid-Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead/Principal"),
                            ("executive", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "remote_policy",
                    models.CharField(
                        choices=[
                            ("onsite", "On-site Only"),
                            ("remote", "Remote Only"),
                            ("hybrid", "Hybrid"),
                            ("flexible", "Flexible"),
                        ],
                        default="onsite",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="ZAR", max_length=3)),
                ("salary_period", models.CharField(default="yearly", max_length=20)),
                ("hide_salary", models.BooleanField(default=False)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("requirements", models.TextField(blank=True, null=True)),
                ("qualifications", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("preferred_skills", models.JSONField(blank=True, default=list)),
                ("min_experience_years", models.IntegerField(default=0)),
                ("positions_available", models.IntegerField(default=1)),
                ("external_apply_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                            ("filled", "Filled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_urgent", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("applications_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
                "db_table": "opportunities",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "db_table": "saved_opportunities",
            },
        ),
    ]
