# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("viewed", "Viewed Only"),
                            ("dismissed", "Dismissed"),
                            ("saved", "Saved"),
                            ("no_action", "No Action"),
                        ],
                        default="no_action",
                        max_length=20,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("feedback_score", models.IntegerField(blank=True, null=True)),
                ("outcome_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "match_history",
                "ordering": ["-outcome_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.FloatField(db_index=True, default=0.0)),
                ("skills_match", models.FloatField(default=0.0)),
                ("experience_match", models.FloatField(default=0.0)),
                ("education_match", models.FloatField(default=0.0)),
                ("location_match", models.FloatField(default=0.0)),
                ("salary_match", models.FloatField(default=0.0)),
                ("culture_match", models.FloatField(default=0.0)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("matched_skills", models.JSONField(blank=True, default=list)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("skill_gap_analysis", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "match_scores",
                "ordering": ["-overall_score"],
            },
        ),
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("talent", "Talent"),
                            ("opportunity", "Opportunity"),
                            ("organization", "Organization"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField(db_index=True)),
                ("search_text", models.TextField(blank=True)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("location_data", models.JSONField(blank=True, default=dict)),
                ("experience_level", models.CharField(blank=True, max_length=50)),
                ("job_types", models.JSONField(blank=True, default=list)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(blank=True, max_length=3)),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("embedding_model", models.CharField(blank=True, max_length=50)),
                ("boost_score", models.FloatField(default=1.0)),
                ("quality_score", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("last_indexed", models.DateTimeField(auto_now=True)),
                ("index_version", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_index",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "is_active"],
                        name="search_inde_entity__1fe44a_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-boost_score"],
                        name="search_inde_is_acti_bf1bd1_idx",
                    ),
                    models.Index(
                        fields=["-last_indexed"], name="search_inde_last_in_e3dd14_idx"
                    ),
                ],
                "unique_together": {("entity_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rec_type",
                    models.CharField(
                        choices=[
                            ("opportunity", "Opportunity"),
                            ("skill", "Skill to Learn"),
                            ("course", "Course"),
                            ("connection", "Connection"),
                            ("content", "Content"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("target_id", models.UUIDField(db_index=True)),
                ("relevance_score", models.FloatField(db_index=True, default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                ("reason", models.TextField(blank=True)),
                ("explanation_data", models.JSONField(blank=True, default=dict)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("is_viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_clicked", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("is_saved", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_score",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="matching.matchscore",
                    ),
                ),
            ],
            options={
                "db_table": "recommendations",
                "ordering": ["user", "-relevance_score", "rank"],
            },
        ),
    ]
