# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchscore",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_scores",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="matchscore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matchhistory",
            name="match_score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="matching.matchscore",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "rec_type", "-relevance_score"],
                name="recommendat_user_id_2873dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "is_dismissed", "-created_at"],
                name="recommendat_user_id_3df15e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["target_id"], name="recommendat_target__cfab1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["-created_at"], name="recommendat_created_b64c7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["user", "-overall_score"], name="match_score_user_id_d26233_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["opportunity", "-overall_score"],
                name="match_score_opportu_5b8be3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["-overall_score"], name="match_score_overall_d03df4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["-calculated_at"], name="match_score_calcula_36e1f2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="matchscore",
            unique_together={("user", "opportunity")},
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["match_score", "-outcome_at"],
                name="match_histo_match_s_36ed7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="matchhistory",
            index=models.Index(
                fields=["outcome"], name="match_histo_outcome_ef7fac_idx"
            ),
        ),
    ]
