# Generated by Django 4.2.29 on 2026-03-25 00:42

from django.db import migrations, models
import media.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaProcessingLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("media_type", models.CharField(max_length=20)),
                ("media_id", models.UUIDField()),
                ("operation", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("input_size", models.BigIntegerField(default=0)),
                ("output_size", models.BigIntegerField(default=0)),
                ("processing_time_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "media_processing_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["media_type", "media_id"],
                        name="media_proce_media_t_590519_idx",
                    ),
                    models.Index(
                        fields=["operation", "status"],
                        name="media_proce_operati_3c7bd2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("owner_type", models.CharField(default="user", max_length=20)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile Photo"),
                            ("cover", "Cover Photo"),
                            ("gallery", "Gallery"),
                            ("logo", "Logo"),
                            ("certificate", "Certificate Image"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "original_file",
                    models.ImageField(
                        blank=True, null=True, upload_to=media.models.image_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("original_size", models.BigIntegerField(default=0)),
                ("original_width", models.IntegerField(default=0)),
                ("original_height", models.IntegerField(default=0)),
                ("mime_type", models.CharField(max_length=100)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("medium_url", models.URLField(blank=True)),
                ("large_url", models.URLField(blank=True)),
                ("full_url", models.URLField(blank=True)),
                ("thumbnail_size", models.BigIntegerField(default=0)),
                ("medium_size", models.BigIntegerField(default=0)),
                ("large_size", models.BigIntegerField(default=0)),
                ("full_size", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Processing Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "images",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner_id", "owner_type", "image_type"],
                        name="images_owner_i_30490c_idx",
                    ),
                    models.Index(fields=["status"], name="images_status_d4e4b1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("cv", "CV/Resume"),
                            ("cover_letter", "Cover Letter"),
                            ("certificate", "Certificate"),
                            ("transcript", "Transcript"),
                            ("portfolio", "Portfolio"),
                            ("id_document", "ID Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=media.models.document_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("original_size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(max_length=100)),
                ("extracted_text", models.TextField(blank=True)),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Processing Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner_id", "document_type"],
                        name="documents_owner_i_64a51a_idx",
                    ),
                    models.Index(fields=["status"], name="documents_status_f31a08_idx"),
                ],
            },
        ),
    ]
